import Link from 'next/link';
import { notFound } from 'next/navigation';
import { getDictionary, isLocale, LOCALES } from '@/lib/i18n';
import { SITE_URL, BUSINESS } from '@/lib/site';
import { services, serviceBySlug, serviceAlternates, serviceUi } from '@/lib/servicePages';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';

export const dynamicParams = false;

export function generateStaticParams({ params }) {
  // Nested params: this runs once per locale generated by the segment above,
  // and each locale has its own slugs so the French URLs carry French words.
  const locales = params?.locale ? [params.locale] : LOCALES;
  return locales.flatMap((locale) =>
    services.map((s) => ({ locale, slug: s.slug[locale] }))
  );
}

export function generateMetadata({ params }) {
  const { locale, slug } = params;
  if (!isLocale(locale)) return {};
  const service = serviceBySlug(locale, slug);
  if (!service) return {};

  const c = service[locale];
  const alt = serviceAlternates(service);

  return {
    title: c.metaTitle,
    description: c.metaDescription,
    alternates: {
      canonical: `/${locale}/services/${slug}`,
      languages: {
        'en-CA': alt.en,
        'fr-CA': alt.fr,
        'x-default': alt.en,
      },
    },
    openGraph: {
      title: c.metaTitle,
      description: c.metaDescription,
      url: `${SITE_URL}/${locale}/services/${slug}`,
      type: 'website',
    },
  };
}

export default function ServicePage({ params }) {
  const { locale, slug } = params;
  if (!isLocale(locale)) notFound();
  const service = serviceBySlug(locale, slug);
  if (!service) notFound();

  const dict = getDictionary(locale);
  const c = service[locale];
  const ui = serviceUi[locale];
  const base = `/${locale}`;
  const others = services.filter((s) => s.id !== service.id);

  const jsonLd = [
    {
      '@context': 'https://schema.org',
      '@type': 'Service',
      name: c.name,
      description: c.metaDescription,
      serviceType: c.name,
      url: `${SITE_URL}/${locale}/services/${slug}`,
      provider: { '@id': `${SITE_URL}/#business` },
      areaServed: BUSINESS.areaServed.map((name) => ({ '@type': 'City', name })),
      availableLanguage: BUSINESS.languages,
    },
    {
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      mainEntity: c.faqs.map((f) => ({
        '@type': 'Question',
        name: f.q,
        acceptedAnswer: { '@type': 'Answer', text: f.a },
      })),
    },
    {
      '@context': 'https://schema.org',
      '@type': 'BreadcrumbList',
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: 'Zyvanta', item: `${SITE_URL}/${locale}` },
        { '@type': 'ListItem', position: 2, name: ui.back, item: `${SITE_URL}/${locale}/services` },
        { '@type': 'ListItem', position: 3, name: c.name },
      ],
    },
  ];

  return (
    <>
      <Nav dict={dict.nav} locale={locale} base={base} />

      <main className="relative z-10 pt-[68px]">
        <section className="container-x py-16 sm:py-24">
          <nav aria-label="Breadcrumb" className="mb-8 text-[12.5px] text-slate-500">
            <Link href={`/${locale}/services`} className="transition-colors hover:text-cyan-glow">
              {ui.back}
            </Link>
            <span className="px-2" aria-hidden="true">/</span>
            <span className="text-slate-400">{c.name}</span>
          </nav>

          <p className="eyebrow">
            <span className="h-px w-8 bg-cyan-core/60" />
            {service.n} · {c.name}
          </p>

          <h1 className="mt-5 max-w-[24ch] font-display text-[clamp(2.1rem,5vw,3.6rem)] font-semibold leading-[1.04] tracking-tightest text-white">
            {c.h1}
          </h1>

          <p className="mt-6 max-w-[60ch] text-[16.5px] leading-relaxed text-slate-400">{c.lede}</p>

          <div className="mt-9 flex flex-wrap gap-3">
            <Link
              href={`${base}#contact`}
              className="rounded-full bg-cyan-core px-6 py-3 text-[14px] font-semibold text-midnight-950 transition-shadow hover:shadow-[0_0_40px_-8px_rgba(34,211,238,0.9)]"
            >
              {ui.cta}
            </Link>
            <Link
              href={`/${locale}/audit`}
              className="rounded-full border border-white/15 px-6 py-3 text-[14px] text-slate-200 transition-colors hover:border-cyan-core/50 hover:text-white"
            >
              {ui.auditCta}
            </Link>
          </div>
        </section>

        <section className="container-x grid gap-10 pb-16 lg:grid-cols-2">
          <div className="rounded-2xl glass p-7 sm:p-9">
            <h2 className="font-display text-[20px] font-semibold text-white">{ui.forWho}</h2>
            <ul className="mt-6 space-y-4">
              {c.forWho.map((item) => (
                <li key={item} className="flex gap-3 text-[15px] leading-relaxed text-slate-300">
                  <span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-cyan-core" aria-hidden="true" />
                  {item}
                </li>
              ))}
            </ul>
          </div>

          <div className="rounded-2xl glass p-7 sm:p-9">
            <h2 className="font-display text-[20px] font-semibold text-white">{ui.includes}</h2>
            <ul className="mt-6 space-y-4">
              {c.includes.map((item) => (
                <li key={item} className="flex gap-3 text-[15px] leading-relaxed text-slate-300">
                  <span className="mt-0.5 shrink-0 text-cyan-core" aria-hidden="true">✓</span>
                  {item}
                </li>
              ))}
            </ul>
          </div>
        </section>

        <section className="container-x py-16">
          <h2 className="font-display text-[clamp(1.5rem,3vw,2.1rem)] font-semibold tracking-tightest text-white">
            {ui.steps}
          </h2>
          <ol className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">
            {c.steps.map((step, i) => (
              <li key={step.t} className="rounded-2xl glass p-6">
                <span className="font-display text-[11px] tracking-[0.3em] text-cyan-core/70">
                  {String(i + 1).padStart(2, '0')}
                </span>
                <h3 className="mt-4 font-display text-[17px] font-semibold text-white">{step.t}</h3>
                <p className="mt-2.5 text-[14px] leading-relaxed text-slate-400">{step.d}</p>
              </li>
            ))}
          </ol>
        </section>

        <section className="container-x py-16">
          <div className="grid gap-10 lg:grid-cols-[minmax(0,0.7fr)_minmax(0,1fr)]">
            <div>
              <h2 className="font-display text-[clamp(1.5rem,3vw,2.1rem)] font-semibold tracking-tightest text-white">
                {ui.faqs}
              </h2>
              <p className="mt-5 max-w-[34ch] text-[14px] leading-relaxed text-slate-500">{c.price}</p>
            </div>

            <div className="divide-y divide-white/8 border-y border-white/8">
              {c.faqs.map((f) => (
                <details key={f.q} className="group py-5">
                  <summary className="flex cursor-pointer list-none items-start justify-between gap-6 text-[16px] font-medium text-white">
                    {f.q}
                    <span className="mt-0.5 shrink-0 text-cyan-core transition-transform duration-300 group-open:rotate-45" aria-hidden="true">
                      +
                    </span>
                  </summary>
                  <p className="mt-3 max-w-[64ch] text-[14.5px] leading-relaxed text-slate-400">{f.a}</p>
                </details>
              ))}
            </div>
          </div>
        </section>

        <section className="container-x py-16">
          <h2 className="font-display text-[20px] font-semibold text-white">{ui.other}</h2>
          <div className="mt-6 grid gap-4 sm:grid-cols-3">
            {others.map((o) => (
              <Link
                key={o.id}
                href={`/${locale}/services/${o.slug[locale]}`}
                className="group rounded-2xl glass p-6 transition-all duration-500 hover:-translate-y-1 hover:border-cyan-core/35"
              >
                <h3 className="font-display text-[16px] font-semibold text-white">{o[locale].name}</h3>
                <p className="mt-2.5 text-[13.5px] leading-relaxed text-slate-400">{o[locale].short}</p>
              </Link>
            ))}
          </div>
        </section>
      </main>

      <Footer dict={dict.footer} nav={dict.nav} locale={locale} base={base} />

      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
    </>
  );
}
